[build]
builder = "NIXPACKS"
buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/api/health"
