[build]
builder = "NIXPACKS"
buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader"

[deploy]
startCommand = "php -S 0.0.0.0:${PORT} -t public"
healthcheckPath = "/api/health"
